<?php

/**
 * Created by PhpStorm.
 * User: mybook-lhp
 * Date: 18/7/2
 * Time: 下午3:39
 */

namespace app\common\controller;

use app\common\apiinit;
use think\Controller;
use think\facade\Request;

class API extends Controller
{
    use apiinit;

    protected $memberId = 0;
    protected $memberInfo = [];
    protected $member_token = '';

    protected $request_data = null;
    protected $PRIVATE = '';
    protected $appVersion = '1.0.0';
    protected $instanceRedis;

    /**
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub";
        $token     = Request::header('token');
        $appConfig = config('app.');
      

    }




    protected function check_validate($data, $type)
    {

        $result = $this->validate($data, $type);
        (true !== $result) ? $this->error($result) : null;
    }




   
}
